name: Podcast API CICD

on:
  push:
    branches: [main]
    paths:
      - "src/Services/Podcasts/**"
      - "deploy/Services/api.bicep"
      - ".github/workflows/podcast-api.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/Services/Podcasts/**"
      - ".github/workflows/podcast-api.yml"

  workflow_dispatch:

jobs:
  buildPushDeployStaging:
    name: "staging"
    if: "!contains(github.ref, 'refs/heads/main')"
    uses: ./.github/workflows/template-api.yml
    concurrency:
      group: staging-api
      cancel-in-progress: true
    secrets: inherit
    with:
      environment: staging

  buildPushDeployProd:
    name: "prod"
    if: contains(github.ref, 'refs/heads/main')
    uses: ./.github/workflows/template-api.yml
    concurrency:
      group: prod-api
      cancel-in-progress: true
    secrets: inherit
    with:
      environment: prod
